import { randomUUID } from 'node:crypto'

const MARKER = 'DEX_DRAFT_STATE='
export const REPO = 'iDevBuddy/dex-website'
export function currentSlot(now = new Date()) {
    const date = new Date(now)
    if (date.getUTCHours() < 9) date.setUTCDate(date.getUTCDate() - 1)
    while (![1, 3, 5].includes(date.getUTCDay())) date.setUTCDate(date.getUTCDate() - 1)
    return date.toISOString().slice(0, 10)
}
export function readState(commit) {
    try { return JSON.parse(commit.message.split(MARKER)[1]) } catch { return null }
}
export function githubClient(token, fetcher = fetch) {
    if (!token) throw new Error('GitHub credential missing')
    return async (path, method = 'GET', body) => {
        const res = await fetcher(`https://api.github.com/repos/${REPO}${path ? `/${path}` : ''}`, {
            method, headers: { Authorization: `Bearer ${token}`, Accept: 'application/vnd.github+json',
                'Content-Type': 'application/json', 'X-GitHub-Api-Version': '2022-11-28', 'User-Agent': 'DEX-Cloud-Drafts' },
            body: body === undefined ? undefined : JSON.stringify(body), signal: AbortSignal.timeout(20000),
        })
        if (!res.ok) { const error = new Error(`GitHub ${method} ${path.split('?')[0]}: HTTP ${res.status}`); error.status = res.status; throw error }
        return res.status === 204 ? null : res.json()
    }
}

async function branchHead(api, branch) {
    try { return (await api(`git/ref/heads/${branch}`)).object.sha } catch (e) { if (e.status === 404) return null; throw e }
}
async function writeState(api, parent, tree, state, title) {
    return api('git/commits', 'POST', { message: `${title}${state.status === 'ready' ? '' : ' [skip ci]'}\n\n${MARKER}${JSON.stringify(state)}`, tree, parents: [parent] })
}
async function moveBranch(api, branch, sha) {
    // Non-force updates reject a stale worker: its commit is not a descendant of the new head.
    return api(`git/refs/heads/${branch}`, 'PATCH', { sha, force: false })
}
export async function claimSlot(api, slot, now = new Date()) {
    const branch = `blog-drafts/${slot}`
    const pulls = await api(`pulls?state=all&head=iDevBuddy:${branch}&base=main&per_page=10`)
    if (pulls.length) return { status: 'already_reviewed_or_queued', url: pulls[0].html_url }
    const existing = await branchHead(api, branch)
    const parent = existing || (await api('git/ref/heads/main')).object.sha
    const commit = await api(`git/commits/${parent}`)
    const previous = existing ? readState(commit) : null
    if (existing && !previous) return { status: 'manual_branch_change' }
    if (previous?.status === 'ready') return { status: 'ready', branch, sha: parent, state: previous }
    if (previous?.status === 'running' && Date.parse(previous.expiresAt) > now.getTime()) return { status: 'busy' }
    if ((previous?.attempt || 0) >= 2) return { status: 'attempt_limit' }
    const state = { slot, status: 'running', owner: randomUUID(), attempt: (previous?.attempt || 0) + 1,
        expiresAt: new Date(now.getTime() + 30 * 60000).toISOString() }
    const next = await writeState(api, parent, commit.tree.sha, state, `chore: reserve draft ${slot}`)
    try {
        if (existing) await moveBranch(api, branch, next.sha)
        else await api('git/refs', 'POST', { ref: `refs/heads/${branch}`, sha: next.sha })
    } catch (e) {
        // Reconcile a timeout before deciding whether our reservation succeeded.
        if (await branchHead(api, branch) !== next.sha) {
            if ([409, 422].includes(e.status)) return { status: 'busy' }
            throw e
        }
    }
    return { status: 'claimed', branch, sha: next.sha, tree: commit.tree.sha, state }
}
export async function openReview(api, branch, state) {
    const existing = await api(`pulls?state=all&head=iDevBuddy:${branch}&base=main&per_page=10`)
    if (existing.length) return { status: 'awaiting_approval', url: existing[0].html_url }
    const report = state.report
    const body = `## Article awaiting your approval\n\n${report.description}\n\n- Research grounded: ${report.grounded === true ? 'yes' : 'needs review'}\n- Fact check: ${report.verdict}\n- Cover: ${report.cover}\n- Audio: not generated by the cloud draft runner\n\n${report.flagged?.length ? '**Check these claims before approving:**\n' + report.flagged.map(x => `- ${String(x.claim).slice(0, 300)} — ${String(x.why).slice(0, 300)}`).join('\n') : ''}\n\nReview the article under **Files changed** (Markdown preview). Edit if needed. **Merge this PR only when you approve publication**; Netlify will then deploy it from main. Close without merging to reject. No automatic merge is configured.\n\nDraft slot: ${state.slot}. Generator: ${state.source}.`
    try {
        const pr = await api('pulls', 'POST', { title: `Blog draft: ${state.title}`, head: branch, base: 'main', body,
            draft: report.grounded !== true || report.verdict !== 'pass' })
        return { status: 'awaiting_approval', url: pr.html_url }
    } catch (e) {
        // The create request may have succeeded even if its response was lost.
        const found = await api(`pulls?state=all&head=iDevBuddy:${branch}&base=main&per_page=10`)
        if (found.length) return { status: 'awaiting_approval', url: found[0].html_url }
        throw e
    }
}
export async function runDraft({ api, generate, now = new Date(), source = 'netlify' }) {
    const claim = await claimSlot(api, currentSlot(now), now)
    if (claim.status === 'ready') return openReview(api, claim.branch, claim.state)
    if (claim.status !== 'claimed') return claim
    let saved = false
    try {
        const tree = await api(`git/trees/${claim.tree}?recursive=1`)
        if (tree.truncated) throw new Error('Repository tree truncated; cannot safely check duplicates')
        const pulls = await api('pulls?state=open&base=main&per_page=100')
        if (pulls.length >= 100) throw new Error('Review queue needs pagination; stop instead of risking duplicates')
        const known = tree.tree.filter(x => /^(content\/blog\/.*\.md|data\/blog\/pending\/.*\.json)$/.test(x.path))
            .map(x => ({ slug: x.path.split('/').at(-1).replace(/\.(md|json)$/, ''), title: x.path.split('/').at(-1).replace(/[-.]/g, ' ') }))
        known.push(...pulls.map(x => ({ title: x.title.replace(/^Blog draft:\s*/, '') })))
        const draft = await generate(known)
        if (!draft?.files?.length || !draft.title) throw new Error('Generator did not produce a draft')
        // Only article/media additions can be written; never workflows or application code.
        const entries = []
        for (const file of draft.files) {
            if (!/^(content\/blog\/[a-z0-9-]+\.md|public\/blog\/images\/[a-z0-9-]+\.png)$/.test(file.path)) throw new Error('Unsafe draft file path')
            if (tree.tree.some(x => x.path === file.path)) throw new Error('Refusing to overwrite existing content')
            const blob = await api('git/blobs', 'POST', { content: file.content, encoding: file.encoding || 'utf-8' })
            entries.push({ path: file.path, mode: '100644', type: 'blob', sha: blob.sha })
        }
        const nextTree = await api('git/trees', 'POST', { base_tree: claim.tree, tree: entries })
        const state = { ...claim.state, status: 'ready', title: draft.title, source, report: draft.report }
        const commit = await writeState(api, claim.sha, nextTree.sha, state, `content: review draft ${claim.state.slot}`)
        try { await moveBranch(api, claim.branch, commit.sha) }
        catch (e) { if (await branchHead(api, claim.branch) !== commit.sha) throw e }
        saved = true
        return await openReview(api, claim.branch, state)
    } catch (e) {
        // Never replace a newer worker's result or a saved article after uncertain API outcomes.
        if (!saved && await branchHead(api, claim.branch) === claim.sha) {
            const failed = await writeState(api, claim.sha, claim.tree, { ...claim.state, status: 'failed', error: 'Generation or persistence failed; see runner logs' }, `chore: draft failed ${claim.state.slot}`)
            await moveBranch(api, claim.branch, failed.sha)
        }
        throw e
    }
}
